version: "3.1"
services:
  www:
    build: .docker
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./public/:/var/www/html
      - ./.docker/conf/xdebug.ini/:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/conf/php.ini/:/usr/local/etc/php/conf.d/php.ini
    links:
      - db
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker

volumes:
  persistent:
